name: Build Cohort Annotation Track
description: Generate or update a cohort allele frequency annotation track from VCF files using the specified cohort definition. If the cohort already exists, a new version is created with merged variant frequencies.

stages:
  - name: VCF Input
    description: Generate manifest file from VCF directory
    task_path: tasks/cohort_manifest.task.yaml
    depends_on: []
    task_parameters:
      - name: input_directory
        label: VCF Input Directory
        help: Directory containing *.vcf.gz files to process
        type: directory
        supports_location_mode: 'read_only'
        persist_key: 'cohorts.input_directory'

      - name: parameter_file
        label: Parameter File
        help: Parameter file for the cohort
        type: file
        persist_key: 'cohorts.parameter_file'

  - name: Process VCF Manifests
    description: Generate manifest file from VCF directory
    task_path: tasks/vcf_import.task.yaml
    depends_on: ['VCF Input']

    glob_parameter:
      path:
        type: 'stage'
        stage: VCF Input
        parameter_expression: ${output_directory}
      glob_ex: '*.manifest.txt'
      output_parameters:
        - task_parameter_name: manifest_file
          expression: '${0}'

    task_parameters:
      - name: parameter_file
        label: Parameter File
        help: Parameter file for the cohort
        type: stage
        stage: VCF Input
        stage_parameter_expression: ${parameter_file}

  - name: Merge Results
    description: Merge the imported VCF results into the combined cohort annotation track
    task_path: tasks/cohort_update.task.yaml
    depends_on: ['Process VCF Manifests']

    task_parameters:
      - name: parameter_file
        label: Parameter File
        help: Parameter file for the cohort
        type: stage
        stage: VCF Input
        stage_parameter_expression: ${parameter_file}

      - name: manifest_parameter_file
        label: Manifest parameter file for cohort annotation track
        type: stage
        stage: VCF Input
        stage_parameter_expression: ${output_manifest_list}


