name: Build Cohort Annotation Track
description: Generate or update a cohort allele frequency annotation track from VCF files using the specified cohort definition. If the cohort already exists, a new version is created with merged variant frequencies.

stages:
  - name: VCF Input
    description: Generate manifest file from VCF directory
    task_path: tasks/cohort_manifest.task.yaml
    depends_on: []
    task_parameters:
      - name: input_directory
        label: VCF Input Directory
        help: Directory containing *.vcf.gz files to process
        type: directory
        supports_location_mode: 'read_only'
        persist_key: 'cohorts.input_directory'

  - name: Process Cohort Annotation Track
    description: Process VCF files and generate variant frequencies
    task_path: tasks/cohort_update.task.yaml
    depends_on: ["VCF Input"]
    parameter_file:
      path: 
        base_path: 
          type: directory
          value: "AppData/Common Data/UserAnnotations/cohorts"
        file: ""

    task_parameters:
      - name: manifest_file
        label: Manifest File
        type: stage
        stage: VCF Input
        stage_parameter_expression: ${manifest_file}

